apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-hello-app
spec:
  containers: 
  - name: result-app
    image: latha123456/hello.jar
    ports :
    - containerPort: 80