apiVersion: v1
kind: Pod
metadata: 
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-hello-app
spec:
  containers: 
  - name: worker-app
    image: latha123456/hello.jar
    